### ISSUE TITLE
Error in 24H2

### ISSUE THREAD

**Issue by AFaustini** [cschneegans/unattend-generator#23] opened 2024-07-19 16:46 UTC
When i select the "Partition the disk interactively during Windows Setup" option, only on 24H2 the new setup experience give me this error: 0x80070490 - 0x4002c
This occurs also without the use of autounattend.xml, and i have to change to "previous version of setup" to install Windows.
There is a way to automate this change?

**Comment by cschneegans** [comment] 2024-07-19 18:52
Sorry, unable to reproduce. I have tested the parameter `PartitionMode=Interactive` with both _Windows11_InsiderPreview_Client_x64_en-us_26080.iso_ and _Windows11_InsiderPreview_Client_x64_en-us_26100_ and did not run into problems.

You can try to analyze the error this way:

1. When the error message appears, press Shift+F10 to open a console window.
2. Type `notepad X:\Windows\setuperr.log` and inspect the log messages, if any
3. Type `notepad X:\Windows\setupact.log` and inspect the log messages, if any

On my system, the output looks as follows:

![Windows 11-2024-07-19-20-45-54](https://github.com/user-attachments/assets/836878a5-c651-4a37-ab1c-83cc6250c8df)

**Comment by AFaustini** [comment] 2024-07-19 20:15
my setupact.log output this
`2024-07-19 17:05:19, Info                  UI     Determining whether we should run ConX or legacy setup
2024-07-19 17:05:20, Info                  UI     Will launch ConX setup experience
2024-07-19 17:05:20, Info                         [setup.exe] UnattendSearchExplicitPath: Found unattend file at [G:\Unattend.xml]; examining for applicability.
2024-07-19 17:05:20, Info                         [setup.exe] UnattendSearchExplicitPath: Found usable unattend file for pass [windowsPE] at [G:\Unattend.xml].
2024-07-19 17:05:20, Info                         [setup.exe] UnattendSearchExplicitPath: Found usable unattend file for pass [offlineServicing] at [G:\Unattend.xml].
2024-07-19 17:05:20, Warning                      [setup.exe] UnattendSearchSetupSourceDrive: Unable to convert ARC path [MULTI(0)DISK(0)CDROM(0)] to NT path; status = 0x80070002.
2024-07-19 17:05:20, Info                  UI     Initializing Media class driver for audio support
2024-07-19 17:05:20, Info                  UI     Initializing media class driver status: 0
2024-07-19 17:05:20, Info                  UI     Launching ConX setup experience
2024-07-19 17:05:20, Info                  UI     Inspecting ConX Setup Cmdline
2024-07-19 17:05:20, Info                  UI     Launching X:\Sources\SetupPrep.exe /boot 
`
But the error continue.
What parameter "PartitionMode=Interactive" should change in XML?

**Comment by cschneegans** [comment] 2024-07-19 21:05
Well, your log is identical to mine, so this does not give me any ideas.

`PartitionMode=Interactive` is just the query string parameter that corresponds to the “Partition the disk interactively during Windows Setup” option.

Can you provide a screenshot of when Windows tells you to switch to the “previous version of setup”? I have never seen this.

**Comment by AFaustini** [comment] 2024-07-19 23:25
![Capture](https://github.com/user-attachments/assets/1b578978-a77e-443d-b28b-8d69d110603c)
on elevenforum (https://www.elevenforum.com/t/w11-24h2-and-old-installation-setup.25706/page-2) some guy told to insert this
        <settings pass="windowsPE">
                <component name="Microsoft-Windows-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
                        <RunSynchronous>
                                <RunSynchronousCommand wcm:action="add">
                                        <Description>Switch to legacy Setup</Description>
                                        <Order>1</Order>
                                        <Path>reg add "HKEY_LOCAL_MACHINE\SYSTEM\Setup" /v CmdLine /t REG_SZ /d "X:\sources\setup.exe" /f</Path>
                                </RunSynchronousCommand>
                        </RunSynchronous>
                </component>
        </settings>

but doesn`t work here too

**Comment by cschneegans** [comment] 2024-07-24 07:03
Couldn't get this it to work either. I ran an unattended installation of _Windows11_InsiderPreview_Client_x64_en-us_26100.iso_ twice in a virtual machine – first without the reg.exe command you posted, then with it. The command was successfully executed, i.e. it set the

```
[HKEY_LOCAL_MACHINE\SYSTEM\Setup]
"CmdLine"="X:\\sources\\setup.exe"
```
registry value in Windows PE. However, this had no effect whatsoever on the setup experience, which used the new UI in both cases:

![conx](https://github.com/user-attachments/assets/428d6fca-9168-4475-b3be-7fadd143b6bc)

Closing, as this is not related to my library and the guys over at [ElevenForum](https://www.elevenforum.com/t/w11-24h2-and-old-installation-setup.25706/) clearly know more about this than me.

**Closed by cschneegans** 2024-07-24 07:03 UTC

**Comment by cschneegans** [comment] 2024-09-12 14:10
I have recently added a new setting to my service: 

![R0IP8fcRlSAADpGb](https://github.com/user-attachments/assets/af30ce4f-8c53-4b80-9251-56ec3687475b)

In particular, this setting can to used to specify an answer file and still run the legacy setup. To do so, proceed as follows:

1. Tick the checkbox to create an answer file named `notautounattend.xml`.
2. Start Windows Setup as usual, choose language and keyboard settings, then click **Previous Version of Setup**.

![image](https://github.com/user-attachments/assets/2948528c-093d-4c1d-b893-e1c4e3ec1413)

3. When the legacy dialog appears, press Shift+F10 to open a console window and type 
```
setup.exe /Unattend:D:\notautounattend.xml
```
where D: is the drive that contains the answer file.

![s4VBxg0Z0T3k5hTL](https://github.com/user-attachments/assets/9033cef1-9ddf-4f57-9b1b-1a5533bafab6)
