### ISSUE TITLE
[FEATURE_REQUEST] Change variable locations

### ISSUE THREAD

**Issue by erwannmag** [cschneegans/unattend-generator#51] opened 2024-09-15 19:07 UTC
Would it be possible to move default variables locations to custom ones, i.e.:

"C:\Users\John Doe\Documents" 

to

"D:\Documents"

And doing this for the others such as Desktop, Music, Images, Downloads, etc.

**Comment by cschneegans** [comment] 2024-09-16 06:16
Duplicate of https://github.com/cschneegans/unattend-generator/issues/46. I have provided a custom script there that performs this modification during Setup. Microsoft strongly advises against relocating the profiles directory.

**Closed** 2024-09-16 06:17 UTC
