### ISSUE TITLE
Prompt for Computer Name

### ISSUE THREAD

**Issue by szilardshomelab** [cschneegans/unattend-generator#74] opened 2024-10-10 19:25 UTC
Hello Sir, 

There is any workaround to prompt for computer name option? 

I tried NTLite and there it's working but Your generator is much more better. :)

**Comment by cschneegans** [comment] 2024-10-10 23:11
Duplicate of #45 and #73. I will continue looking for a solution, but for the time being, you have to

- edit the `<ComputerName>` element before Windows Setup starts, or
- add a custom .ps1 script in the **Scripts to run when the first user logs on after Windows has been installed** section that calls `Restart-Computer`

**Comment by cschneegans** [comment] 2024-10-11 21:54
Just added a new setting **Provide a PowerShell script to set the computer name dynamically**, which you may find interesting:

![image](https://github.com/user-attachments/assets/fe79495b-fd27-4277-a755-19f3f010e092)

**Comment by szilardshomelab** [comment] 2024-10-14 18:06
Thank you! I tried but unfortunately I received the following error:

Get-Content : Cannot find path 'C:\Windows\Setup\Scripts\GetComputerName.ps1' because it does not exist.
At line:1 char:5
+ & { Get-Content -LiteralPath 'C:\Windows\Setup\Scripts\GetComputerNam ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Windows\Setu...omputerName.ps1:String) [Get-Content], ItemNotFoundEx 
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

**Comment by cschneegans** [comment] 2024-10-15 00:31
Well, that's not supposed to happen. Please attach your autounattend.xml file. Also, a directory listing of the `C:\Windows\Setup\Scripts` folder could be helpful.

**Comment by szilardshomelab** [comment] 2024-10-15 04:56
> Well, that's not supposed to happen. Please attach your autounattend.xml file. Also, a directory listing of the `C:\Windows\Setup\Scripts` folder could be helpful.

Here is my unattended.xml:


```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<unattend xmlns="urn:schemas-microsoft-com:unattend" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State">
<!-- https://schneegans.de/windows/unattend-generator/?LanguageMode=Unattended&UILanguage=en-US&Locale=en-US&Keyboard=00000409&UseKeyboard2=true&Locale2=de-DE&Keyboard2=00000407&UseKeyboard3=true&Locale3=hu-HU&Keyboard3=0000040e&GeoLocation=94&ProcessorArchitecture=amd64&ComputerNameMode=Script&ComputerNameScript=return+Read-Host+-Prompt+%27Enter+computer+name%27%3B&CompactOsMode=Default&TimeZoneMode=Explicit&TimeZone=W.+Europe+Standard+Time&PartitionMode=Unattended&PartitionLayout=GPT&EspSize=300&RecoveryMode=Partition&RecoverySize=1000&WindowsEditionMode=Unattended&WindowsEdition=pro&UserAccountMode=Unattended&AccountName0=admin&AccountPassword0=dell%2B1&AccountGroup0=Administrators&AccountName1=&AccountName2=&AccountName3=&AccountName4=&AutoLogonMode=Own&PasswordExpirationMode=Unlimited&LockoutMode=Default&HideFiles=Hidden&TaskbarSearch=Box&VirtIoGuestTools=true&WifiMode=Interactive&ExpressSettings=DisableAll&KeysMode=Skip&ColorMode=Default&WallpaperMode=Default&StartTilesMode=Default&StartPinsMode=Default&WdacMode=Skip -->
<settings pass="offlineServicing"/>
<settings pass="windowsPE">
<component name="Microsoft-Windows-International-Core-WinPE" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
<SetupUILanguage>
<UILanguage>en-US</UILanguage>
</SetupUILanguage>
<InputLocale>0409:00000409;0407:00000407;040e:0000040e</InputLocale>
<SystemLocale>en-US</SystemLocale>
<UILanguage>en-US</UILanguage>
<UserLocale>en-US</UserLocale>
</component>
<component name="Microsoft-Windows-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
<ImageInstall>
<OSImage>
<InstallTo>
<DiskID>0</DiskID>
<PartitionID>3</PartitionID>
</InstallTo>
</OSImage>
</ImageInstall>
<UserData>
<ProductKey>
<Key>VK7JG-NPHTM-C97JM-9MPGT-3V66T</Key>
</ProductKey>
<AcceptEula>true</AcceptEula>
</UserData>
<RunSynchronous>
<RunSynchronousCommand wcm:action="add">
<Order>1</Order>
<Path>cmd.exe /c ">>"X:\diskpart.txt" echo SELECT DISK=0"</Path>
</RunSynchronousCommand>
<RunSynchronousCommand wcm:action="add">
<Order>2</Order>
<Path>cmd.exe /c ">>"X:\diskpart.txt" echo CLEAN"</Path>
</RunSynchronousCommand>
<RunSynchronousCommand wcm:action="add">
<Order>3</Order>
<Path>cmd.exe /c ">>"X:\diskpart.txt" echo CONVERT GPT"</Path>
</RunSynchronousCommand>
<RunSynchronousCommand wcm:action="add">
<Order>4</Order>
<Path>cmd.exe /c ">>"X:\diskpart.txt" echo CREATE PARTITION EFI SIZE=300"</Path>
</RunSynchronousCommand>
<RunSynchronousCommand wcm:action="add">
<Order>5</Order>
<Path>cmd.exe /c ">>"X:\diskpart.txt" echo FORMAT QUICK FS=FAT32 LABEL="System""</Path>
</RunSynchronousCommand>
<RunSynchronousCommand wcm:action="add">
<Order>6</Order>
<Path>cmd.exe /c ">>"X:\diskpart.txt" echo CREATE PARTITION MSR SIZE=16"</Path>
</RunSynchronousCommand>
<RunSynchronousCommand wcm:action="add">
<Order>7</Order>
<Path>cmd.exe /c ">>"X:\diskpart.txt" echo CREATE PARTITION PRIMARY"</Path>
</RunSynchronousCommand>
<RunSynchronousCommand wcm:action="add">
<Order>8</Order>
<Path>cmd.exe /c ">>"X:\diskpart.txt" echo SHRINK MINIMUM=1000"</Path>
</RunSynchronousCommand>
<RunSynchronousCommand wcm:action="add">
<Order>9</Order>
<Path>cmd.exe /c ">>"X:\diskpart.txt" echo FORMAT QUICK FS=NTFS LABEL="Windows""</Path>
</RunSynchronousCommand>
<RunSynchronousCommand wcm:action="add">
<Order>10</Order>
<Path>cmd.exe /c ">>"X:\diskpart.txt" echo CREATE PARTITION PRIMARY"</Path>
</RunSynchronousCommand>
<RunSynchronousCommand wcm:action="add">
<Order>11</Order>
<Path>cmd.exe /c ">>"X:\diskpart.txt" echo FORMAT QUICK FS=NTFS LABEL="Recovery""</Path>
</RunSynchronousCommand>
<RunSynchronousCommand wcm:action="add">
<Order>12</Order>
<Path>cmd.exe /c ">>"X:\diskpart.txt" echo SET ID="de94bba4-06d1-4d40-a16a-bfd50179d6ac""</Path>
</RunSynchronousCommand>
<RunSynchronousCommand wcm:action="add">
<Order>13</Order>
<Path>cmd.exe /c ">>"X:\diskpart.txt" echo GPT ATTRIBUTES=0x8000000000000001"</Path>
</RunSynchronousCommand>
<RunSynchronousCommand wcm:action="add">
<Order>14</Order>
<Path>cmd.exe /c "diskpart.exe /s "X:\diskpart.txt" >>"X:\diskpart.log" || ( type "X:\diskpart.log" & echo diskpart encountered an error. & pause & exit /b 1 )"</Path>
</RunSynchronousCommand>
</RunSynchronous>
</component>
</settings>
<settings pass="generalize"/>
<settings pass="specialize">
<component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
<ComputerName>TEMPNAME</ComputerName>
<TimeZone>W. Europe Standard Time</TimeZone>
</component>
<component name="Microsoft-Windows-Deployment" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
<RunSynchronous>
<RunSynchronousCommand wcm:action="add">
<Order>1</Order>
<Path>powershell.exe -NoProfile -Command "$xml = [xml]::new(); $xml.Load('C:\Windows\Panther\unattend.xml'); $sb = [scriptblock]::Create( $xml.unattend.Extensions.ExtractScript ); Invoke-Command -ScriptBlock $sb -ArgumentList $xml;"</Path>
</RunSynchronousCommand>
<RunSynchronousCommand wcm:action="add">
<Order>2</Order>
<Path>powershell.exe -NoProfile -Command "& { Get-Content -LiteralPath 'C:\Windows\Setup\Scripts\GetComputerName.ps1' -Raw | Invoke-Expression > C:\Windows\Setup\Scripts\ComputerName.txt; } *>&1 >> 'C:\Windows\Setup\Scripts\GetComputerName.log';"</Path>
</RunSynchronousCommand>
<RunSynchronousCommand wcm:action="add">
<Order>3</Order>
<Path>cmd.exe /c start /MIN powershell.exe -NoProfile -Command "Get-Content -LiteralPath 'C:\Windows\Setup\Scripts\SetComputerName.ps1' -Raw | Invoke-Expression;"</Path>
</RunSynchronousCommand>
<RunSynchronousCommand wcm:action="add">
<Order>4</Order>
<Path>net.exe accounts /maxpwage:UNLIMITED</Path>
</RunSynchronousCommand>
<RunSynchronousCommand wcm:action="add">
<Order>5</Order>
<Path>powershell.exe -NoProfile -Command "Get-Content -LiteralPath '%TEMP%\VirtIoGuestTools.ps1' -Raw | Invoke-Expression;"</Path>
</RunSynchronousCommand>
<RunSynchronousCommand wcm:action="add">
<Order>6</Order>
<Path>reg.exe load "HKU\DefaultUser" "C:\Users\Default\NTUSER.DAT"</Path>
</RunSynchronousCommand>
<RunSynchronousCommand wcm:action="add">
<Order>7</Order>
<Path>reg.exe add "HKU\DefaultUser\Software\Microsoft\Windows\CurrentVersion\RunOnce" /v "UnattendedSetup" /t REG_SZ /d "powershell.exe -NoProfile -Command \"Get-Content -LiteralPath 'C:\Windows\Setup\Scripts\UserOnce.ps1' -Raw | Invoke-Expression;\"" /f</Path>
</RunSynchronousCommand>
<RunSynchronousCommand wcm:action="add">
<Order>8</Order>
<Path>reg.exe unload "HKU\DefaultUser"</Path>
</RunSynchronousCommand>
</RunSynchronous>
</component>
</settings>
<settings pass="auditSystem"/>
<settings pass="auditUser"/>
<settings pass="oobeSystem">
<component name="Microsoft-Windows-International-Core" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
<InputLocale>0409:00000409;0407:00000407;040e:0000040e</InputLocale>
<SystemLocale>en-US</SystemLocale>
<UILanguage>en-US</UILanguage>
<UserLocale>en-US</UserLocale>
</component>
<component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
<UserAccounts>
<LocalAccounts>
<LocalAccount wcm:action="add">
<Name>admin</Name>
<Group>Administrators</Group>
<Password>
<Value>something</Value>
<PlainText>true</PlainText>
</Password>
</LocalAccount>
</LocalAccounts>
</UserAccounts>
<AutoLogon>
<Username>admin</Username>
<Enabled>true</Enabled>
<LogonCount>1</LogonCount>
<Password>
<Value>dell+1</Value>
<PlainText>true</PlainText>
</Password>
</AutoLogon>
<OOBE>
<ProtectYourPC>3</ProtectYourPC>
<HideEULAPage>true</HideEULAPage>
<HideWirelessSetupInOOBE>false</HideWirelessSetupInOOBE>
<HideOnlineAccountScreens>false</HideOnlineAccountScreens>
</OOBE>
<FirstLogonCommands>
<SynchronousCommand wcm:action="add">
<Order>1</Order>
<CommandLine>reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon" /v AutoLogonCount /t REG_DWORD /d 0 /f</CommandLine>
</SynchronousCommand>
</FirstLogonCommands>
</component>
</settings>
<Extensions xmlns="https://schneegans.de/windows/unattend-generator/">
<ExtractScript> param( [xml] $Document ); $scriptsDir = 'C:\Windows\Setup\Scripts\'; foreach( $file in $Document.unattend.Extensions.File ) { $path = [System.Environment]::ExpandEnvironmentVariables( $file.GetAttribute( 'path' ) ); if( $path.StartsWith( $scriptsDir ) ) { mkdir -Path $scriptsDir -ErrorAction 'SilentlyContinue'; } $encoding = switch( [System.IO.Path]::GetExtension( $path ) ) { { $_ -in '.ps1', '.xml' } { [System.Text.Encoding]::UTF8; } { $_ -in '.reg', '.vbs', '.js' } { [System.Text.UnicodeEncoding]::new( $false, $true ); } default { [System.Text.Encoding]::Default; } }; [System.IO.File]::WriteAllBytes( $path, ( $encoding.GetPreamble() + $encoding.GetBytes( $file.InnerText.Trim() ) ) ); } </ExtractScript>
<File path="C:\Windows\Setup\Scripts\GetComputerName.ps1"> return Read-Host -Prompt 'Enter computer name'; </File>
<File path="C:\Windows\Setup\Scripts\SetComputerName.ps1"> $newName = Get-Content -LiteralPath 'C:\Windows\Setup\Scripts\ComputerName.txt' -Raw; $ErrorActionPreference = 'Stop'; Set-StrictMode -Version 'Latest'; & { $newName = $newName.Trim(); if( [string]::IsNullOrWhitespace( $newName ) ) { throw "No computer name was provided."; } $keys = @( @{ LiteralPath = 'Registry::HKLM\SYSTEM\CurrentControlSet\Control\ComputerName\ComputerName'; Name = 'ComputerName'; }; @{ LiteralPath = 'Registry::HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters'; Name = 'Hostname'; }; @{ LiteralPath = 'Registry::HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters'; Name = 'NV Hostname'; }; ); while( $true ) { foreach( $key in $keys ) { Set-ItemProperty @key -Type 'String' -Value $newName; } Start-Sleep -Milliseconds 50; } } *>&1 >> 'C:\Windows\Setup\Scripts\SetComputerName.log'; </File>
<File path="%TEMP%\VirtIoGuestTools.ps1"> & { foreach( $letter in 'DEFGHIJKLMNOPQRSTUVWXYZ'.ToCharArray() ) { $exe = "${letter}:\virtio-win-guest-tools.exe"; if( Test-Path -LiteralPath $exe ) { Start-Process -FilePath $exe -ArgumentList '/passive', '/norestart' -Wait; return; } } 'VirtIO Guest Tools image (virtio-win-*.iso) is not attached to this VM.'; } *>&1 >> "$env:TEMP\VirtIoGuestTools.log"; </File>
<File path="C:\Windows\Setup\Scripts\UserOnce.ps1"> & { Set-WinHomeLocation -GeoId 94; Set-ItemProperty -LiteralPath 'Registry::HKCU\Software\Microsoft\Windows\CurrentVersion\Search' -Name 'SearchboxTaskbarMode' -Type 'DWord' -Value 2; } *>&1 >> "$env:TEMP\UserOnce.log"; </File>
</Extensions>
</unattend>
``` 

And here is the folder:
<img width="536" alt="image" src="https://github.com/user-attachments/assets/51ec5efe-0865-45e9-a32e-6d1f642a8129">


The Windows was installed with OSDCloud.

**Comment by cschneegans** [comment] 2024-10-15 10:10
There should be a file `GetComputerName.ps1`, not `GetComputerName.txt`.

**Comment by szilardshomelab** [comment] 2024-10-15 10:15
> There should be a file `GetComputerName.ps1`, not `GetComputerName.txt`.

I tried one more time to install but again I have that txt instead of powershell script.

**Comment by cschneegans** [comment] 2024-10-15 12:07
There must be some other software interfering with the setup. Just for debugging purposes, run this command from the autounattend.xml in an elevated PowerShell session:

```
$xml = [xml]::new(); $xml.Load('C:\Windows\Panther\unattend.xml'); $sb = [scriptblock]::Create( $xml.unattend.Extensions.ExtractScript ); Invoke-Command -ScriptBlock $sb -ArgumentList $xml;
```
Does the file `C:\Windows\Setup\Scripts\GetComputerName.ps1` now?

**Comment by szilardshomelab** [comment] 2024-10-15 12:20
Yeah now I have:
<img width="644" alt="image" src="https://github.com/user-attachments/assets/3647cd33-b545-4d88-9ddb-ddbbd22b25b5">

**Comment by cschneegans** [comment] 2024-10-15 12:48
So it seems that someone or something meddles with the files in the `C:\Windows\Setup\Scripts` directory. I think you might find the culprit when you inspect the `SetupComplete.cmd` and `SetupComplete.ps1` files.

**Comment by cschneegans** [comment] 2024-10-15 14:19
> Hmmm so these 2 files are not made by You.

Correct. What is their content?

**Comment by szilardshomelab** [comment] 2024-10-15 14:26
cmd

```
%windir%\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy ByPass -File C:\Windows\Setup\scripts\SetupComplete.ps1

``` 

ps1

```
Write-Output 'Starting SetupComplete Script Process'
Set-ExecutionPolicy RemoteSigned -Force -Scope CurrentUser
$StartTime = Get-Date; Write-Host "Start Time: $($StartTime.ToString("hh:mm:ss"))"
$ModulePath = (Get-ChildItem -Path "$($Env:ProgramFiles)\WindowsPowerShell\Modules\osd" | Where-Object {$_.Attributes -match "Directory"} | select -Last 1).fullname
import-module "$ModulePath\OSD.psd1" -Force
Invoke-Expression (Invoke-RestMethod -Uri 'https://raw.githubusercontent.com/OSDeploy/OSD/master/cloud/modules/_anywhere.psm1')
Start-Sleep -Seconds 10
Start-Transcript -Path 'C:\OSDCloud\Logs\SetupComplete.log' -ErrorAction Ignore
Write-Output 'Setting PowerPlan to High Performance'
powercfg /setactive DED574B5-45A0-4F42-8737-46345C09C238
Write-Output 'Confirming PowerPlan [powercfg /getactivescheme]'
powercfg /getactivescheme
powercfg -x -standby-timeout-ac 0
powercfg -x -standby-timeout-dc 0
powercfg -x -hibernate-timeout-ac 0
powercfg -x -hibernate-timeout-dc 0
Set-PowerSettingSleepAfter -PowerSource AC -Minutes 0
Set-PowerSettingTurnMonitorOffAfter -PowerSource AC -Minutes 0
Write-Output 'Setting Windows OEM Activation [Set-WindowsOEMActivation]'
Set-WindowsOEMActivation
Write-Output '-------------------------------------------------------------'
Write-OutPut 'Running Scripts in Custom OSDCloud SetupComplete Folder'
$SetupCompletePath = "C:\OSDCloud\Scripts\SetupComplete\SetupComplete.cmd"
if (Test-Path $SetupCompletePath){$SetupComplete = Get-ChildItem $SetupCompletePath -Filter SetupComplete.cmd}
if ($SetupComplete){cmd.exe /start /wait /c $SetupComplete.FullName}
Write-Output '-------------------------------------------------------------'
Write-Output 'Setting PowerPlan to Balanced'
Set-PowerSettingTurnMonitorOffAfter -PowerSource AC -Minutes 15
powercfg /setactive 381B4222-F694-41F0-9685-FF5BB260DF2E
$EndTime = Get-date; Write-Host "End Time: $($EndTime.ToString("hh:mm:ss"))"
$TotalTime = New-TimeSpan -Start $StartTime -End $EndTime; $RunTimeMinutes = [math]::round($TotalTime.TotalMinutes,0); Write-Host "Run Time: $RunTimeMinutes Minutes"
Stop-Transcript
Restart-Computer -Force

```

**Comment by cschneegans** [comment] 2024-10-15 14:47
Neither `SetupComplete.cmd` nor `SetupComplete.ps1` contain commands that remove files in `C:\Windows\Setup\Scripts`, but OSDCloud obviously adds more scripts to the machine, including those in `C:\Program Files\WindowsPowerShell\Modules\osd` or `C:\OSDCloud`. You should run the installation without OSDCloud for comparison.

**Comment by szilardshomelab** [comment] 2024-10-15 14:59
In this case I will try to add a powershell script to rename the client. Without OSDCloud it's working fine.

**Closed** 2024-10-19 09:38 UTC
