### ISSUE TITLE
[Feature request] Add OEMInformation RegisteredOwner and RegisteredOrganization 

### ISSUE THREAD

**Issue by 1900forever** [cschneegans/unattend-generator#38] opened 2024-08-22 13:42 UTC
Could you add OEMInformation RegisteredOwner and RegisteredOrganization sections into this tool?

**Comment by cschneegans** [comment] 2024-08-22 14:13
Duplicate of https://github.com/cschneegans/unattend-generator/issues/14?!

**Closed** 2024-08-23 13:30 UTC
